# EC2의 Nginx 설정 (/etc/nginx/conf.d/gsc.conf)
server {
  listen 80;
  server_name _;

  # CloudFront로부터 /api/* 요청을 받아
  # 3000번 포트(백엔드 컨테이너)로 전달
  location /api {
    proxy_pass http://127.0.0.1:3000/;
    
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection 'upgrade';
    proxy_set_header Host $host;
    proxy_cache_bypass $http_upgrade;
  }
  # 방금 추가
  location / {
      return 200 'GSC Portal API Running';
      add_header Content-Type text/plain;
}