upstream blue_backend {
    server 127.0.0.1:3000;
}
upstream green_backend {
    server 127.0.0.1:4000;
}
server {
  listen 80;
  server_name _;

  location / {
    proxy_pass http://127.0.0.1:5173;
  }

  location /api {
    proxy_pass http://127.0.0.1:3000;
    
    # 3000(백엔드)이 웹소켓을 쓴다면 이 설정들을 추가
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection 'upgrade';
    proxy_set_header Host $host;
    proxy_cache_bypass $http_upgrade;
  }
}